include(FindPackageHandleStandardArgs)
find_program(R_EXECUTABLE R)
if(R_EXECUTABLE)
    execute_process(COMMAND "${R_EXECUTABLE} RHOME" OUTPUT_VARIABLE R_HOME_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
    execute_process(COMMAND "${R_EXECUTABLE} RHOME" OUTPUT_VARIABLE R_HOME_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
#  set(R_HOME ${R_BASE_DIR} CACHE PATH "R home directory obtained from R RHOME")
#  mark_as_advanced(R_HOME)
#message(${R_HOME_DIR})
    set(_cmd "${R_EXECUTABLE} --slave -e \"print(Sys.getenv(\\\"R_INfCLUDE_DIR\\\"))\"")
#message(${_cmd})
    execute_process(COMMAND ${_cmd} OUTPUT_VARIABLE _tempstr)
message(STATUS ${_tempstr})
#[1] "/usr/share/R/include"
#    string(REGEX REPLACE "[ ]*(R_LIBS_USER)[ ]*\n\"(.*)\"" "\\2"   R_LIBS_USER ${_rlibsuser})

#  string(LENGTH ${_tempstr} _strlen)
#  string(SUBSTRING ${_tempstr} 4 ${_strlen} ${_tempstr})
#  string(STRIP ${_tempstr} ${_tempstr})
#message(${_strlen})
    set(R_INCLUDE_DIR /usr/share/R/include)
    list(APPEND R_INCLUDE_DIRS ${R_INCLUDE_DIR})
endif(R_EXECUTABLE)

find_program(RSCRIPT_EXECUTABLE Rscript)
find_library(R_LIBRARIES R PATHS ${R_HOME_DIR} PATH_SUFFIXES lib bin/i386)
mark_as_advanced(R_EXECUTABLE R_INCLUDE_DIRS R_LIBRARIES)
find_package_handle_standard_args(R DEFAULT_MSG R_EXECUTABLE R_INCLUDE_DIRS R_LIBRARIES)
